"""
Data models for the VLM-based Planner module.

This module defines all the data structures used by the planner system including
action types, action plans, and session state management.

Note: Detection-related classes (DetectionResult, FrameDetection, ScanResult) are 
defined in the navigation module's tello_nav_extra.py to keep detection functionality
closely integrated with the scan operations.
"""

from enum import Enum
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from datetime import datetime


class PlannerActionType(Enum):
    """
    Enumeration of available actions that the VLM planner can use.
    
    These actions correspond to methods available in the navigation module
    and the enhanced scan functionality.
    """
    NAVIGATE_TO_WAYPOINT = "navigate_to_waypoint"  # Navigate to a specific waypoint
    SCAN_AREA = "scan_area"                        # Scan the current location for objects
    RETURN_TO_START = "return_to_start"            # Return to the START waypoint
    LAND = "land"                                  # Land the drone and end session
    TAKEOFF = "takeoff"                            # Takeoff the drone


class PlannerState(Enum):
    """
    State machine states for the planner executor.
    """
    IDLE = "idle"                                  # Initial state, waiting for task
    PLANNING = "planning"                          # VLM is generating action plan
    EXECUTING = "executing"                        # Executing planned actions
    AWAITING_CONFIRMATION = "awaiting_confirmation"  # Waiting for user to confirm detected object
    REPLANNING = "replanning"                      # VLM is regenerating plan after rejection
    OBJECT_FOUND = "object_found"                  # Target object has been found and confirmed
    OBJECT_NOT_FOUND = "object_not_found"          # All waypoints exhausted, object not found
    RETURNING = "returning"                        # Drone is returning to start
    COMPLETED = "completed"                        # Session completed
    ERROR = "error"                                # Error state


@dataclass
class PlannerAction:
    """
    Represents a single action in the VLM-generated plan.
    
    Attributes:
        action_type: The type of action to perform
        waypoint_name: Target waypoint for navigation actions (optional)
        parameters: Additional parameters for the action
        reason: VLM's reasoning for this action
    """
    action_type: PlannerActionType
    waypoint_name: Optional[str] = None
    parameters: Dict[str, Any] = field(default_factory=dict)
    reason: str = ""
    
    def to_dict(self) -> Dict:
        return {
            'action_type': self.action_type.value,
            'waypoint_name': self.waypoint_name,
            'parameters': self.parameters,
            'reason': self.reason
        }
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'PlannerAction':
        """Create a PlannerAction from a dictionary."""
        return cls(
            action_type=PlannerActionType(data.get('action_type', 'navigate_to_waypoint')),
            waypoint_name=data.get('waypoint_name'),
            parameters=data.get('parameters', {}),
            reason=data.get('reason', '')
        )


@dataclass
class ActionPlan:
    """
    Complete action plan generated by the VLM.
    
    Attributes:
        target_object: The object name to search for (COCO class or custom name)
        is_coco_class: Whether target_object is a COCO 80-class (uses standard YOLO vs YOLO-World)
        related_objects: For non-COCO objects, list of related names to improve detection
        user_description: The original user description (e.g., "red coffee cup")
        actions: Ordered list of actions to execute
        reasoning: VLM's overall reasoning for the plan
        generated_at: Timestamp when plan was generated
    """
    target_object: str
    actions: List[PlannerAction]
    is_coco_class: bool = True  # If True, use scan_with_detection; if False, use scan_with_any_detection
    related_objects: List[str] = field(default_factory=list)  # For non-COCO: synonyms/related terms
    user_description: str = ""
    reasoning: str = ""
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def get_detection_targets(self) -> List[str]:
        """
        Get the list of object names to use for detection.
        
        For COCO classes: returns [target_object]
        For non-COCO: returns [target_object] + related_objects
        """
        if self.is_coco_class:
            return [self.target_object]
        else:
            # Include target_object plus all related objects
            targets = [self.target_object]
            targets.extend([obj for obj in self.related_objects if obj not in targets])
            return targets
    
    def to_dict(self) -> Dict:
        return {
            'target_object': self.target_object,
            'is_coco_class': self.is_coco_class,
            'related_objects': self.related_objects,
            'user_description': self.user_description,
            'actions': [action.to_dict() for action in self.actions],
            'reasoning': self.reasoning,
            'generated_at': self.generated_at
        }
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'ActionPlan':
        """Create an ActionPlan from a dictionary."""
        actions = [PlannerAction.from_dict(a) for a in data.get('actions', [])]
        return cls(
            target_object=data.get('target_object', ''),
            actions=actions,
            is_coco_class=data.get('is_coco_class', True),
            related_objects=data.get('related_objects', []),
            user_description=data.get('user_description', ''),
            reasoning=data.get('reasoning', ''),
            generated_at=data.get('generated_at', datetime.now().isoformat())
        )


@dataclass
class PlannerSessionResult:
    """
    Final result of a complete planner session.
    
    Attributes:
        success: Whether the target object was found and confirmed
        target_object: The object that was searched for
        found_at_waypoint: Waypoint where object was found (if successful)
        waypoints_visited: List of all waypoints visited during the session
        scans_performed: Number of scan operations performed
        object_description: VLM description of the found object (if confirmed)
        session_duration: Total session duration in seconds
        round_durations: Per-round durations in seconds (1 or 2 elements)
        final_state: The final state of the planner
        error_message: Error message if session ended in error state
    """
    success: bool
    target_object: str
    found_at_waypoint: Optional[str] = None
    waypoints_visited: List[str] = field(default_factory=list)
    scans_performed: int = 0
    object_description: Optional[str] = None
    session_duration: float = 0.0
    round_durations: List[float] = field(default_factory=list)
    final_state: PlannerState = PlannerState.COMPLETED
    error_message: Optional[str] = None
    
    def to_dict(self) -> Dict:
        return {
            'success': self.success,
            'target_object': self.target_object,
            'found_at_waypoint': self.found_at_waypoint,
            'waypoints_visited': self.waypoints_visited,
            'scans_performed': self.scans_performed,
            'object_description': self.object_description,
            'session_duration': self.session_duration,
            'final_state': self.final_state.value,
            'error_message': self.error_message
        }
